### ISSUE TITLE
Add Github repo metadata: description, website, and topics

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-status#6]
To :heavy_check_mark: another box on [the list](https://github.com/minvws/nl-covid19-notification-app-dashboard/community)

My proposal would be:
**Description:** "🚦-dashboard to keep track of the app status of features"
**Website:** [`https://minvws.github.io/nl-covid19-notification-app-dashboard/`](https://minvws.github.io/nl-covid19-notification-app-dashboard/)
**Topics:** [`covid-19`](https://github.com/topics/covid-19), [`project-management`](https://github.com/topics/project-management), [`jekyll`](https://github.com/topics/jekyll)

**Comment by jsoeterbroek** [comment]
Updated github repo metadata with description and topics.
